spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
  datasource:
    #h2 console path : jdbc:h2:{~/IdeaProjects/escape-api}/src/test/resources/escape
    url: jdbc:h2:file:./src/test/resources/escape #classpath는 동작하지 않음, 어쩔수 없이 상대경로로 한다..
    driver-class-name: org.h2.Driver
    #이 파일들내에 존재하는 쿼리를 실행시킨후 테스트를 진행함
    #data: classpath*:/users.sql, classpath*:/problems.sql, classpath*:/missions.sql, classpath*:/entry.sql, classpath*:/solved_problem.sql

observing:
  page:
  noticeRoomNo:

app:
  telegram:
    name:
    token:

  admin:
    ids:

  master:
    id:
    pw:
    name:

  selenium:
    driverPath:
