spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~/db/escape
    driver-class-name: org.h2.Driver
#    data: classpath*:/users.sql, classpath*:/problems.sql, classpath*:/missions.sql, classpath*:/entry.sql, classpath*:/solved_problem.sql #이 파일들내에 존재하는 쿼리를 실행시킨후 테스트를 진행함


telegram:
  bot:
    name:
    token:

observer:
  admins:

master:
  id:
  pw:
  name:

observing:
  page:
  noticeRoomNo:

app:
  telegramBot:
    name:
    token:

  admin:
    ids:

  master:
    id:
    pw:
    name:
